version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data/:/var/lib/postgresql/data
      - ./db/dump/:/tmp/dump
    ports:
      - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  postgraphile:
    build: ./postgraphile
    ports:
      - "5000:5000"
    depends_on:
      - db
  hasura:
    build: ./hasura
    ports:
      - "8080:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    depends_on:
      - db
  superset:
    image: tylerfowler/superset
    ports:
      - "8088:8088"
    depends_on:
      - db
  # strapi:
  #   image: strapi/strapi
  #   depends_on:
  #     - db
  #   ports:
  #     - 1337:1337
  #   environment:
  #     - APP_NAME=strapi-app
  #     - DATABASE_CLIENT=postgres
  #     - DATABASE_HOST=db
  #     - DATABASE_PORT=5432
  #     - DATABASE_USERNAME=postgres
  #     - DATABASE_PASSWORD=password
  #     - DATABASE_NAME=strapi
  #   volumes:
  #     - ./db/strapi-app/:/usr/src/api/strapi-app
